import React from 'react';

export type ComponentId = 'agent' | 'edge-router' | 'tesla-auth' | 'vdes-controller' | 'vdes-modem' | 'vde-air' | 'shore-base' | 'shore-router' | 'dest-agent';

export type Language = 'it' | 'en';

export interface TranslationSet {
  title: string;
  subtitle: string;
  engineeringNote: string;
  securityCompliance: string;
  useCases: string;
  closeDocumentation: string;
  protocolArchitecture: string;
  bitLevelMapping: string;
  smartRoutingEnabled: string;
  encapsulationHierarchy: string;
  payloadSpecs: string;
  packetField: string;
   bitByteSize: string;
   logicDescription: string;
   referenceLibrary: string;
   innerCore: string;
   carrierLayer: string;
   middleware: string;
   ipLink: string;
   vdesLink: string;
   activeProtocol: string;
   details: string;
   smartRoutingNote: string;
   specification: string;
   vdesDescription: string;
   architectureView: string;
   vdesStructureView: string;
   frequency: string;
   channel: string;
   purpose: string;
   modulation: string;
   technology: string;
   upperLeg: string;
   lowerLeg: string;
   simplex: string;
   power: string;
   functioningLogic: string;
   routingLogic: string;
   messageBroker: string;
   storeAndForward: string;
   failoverMechanisms: string;
   confidentiality: string;
   integrity: string;
   availability: string;
   securityAnalysis: string;
   simulationView: string;
   activeScenario: string;
   satLossScenario: string;
   cyberScenario: string;
   startSimulation: string;
   stopSimulation: string;
   simEventLog: string;
   coastalRange: string;
   deepSea: string;
   shipStatus: string;
   linkStatus: string;
   securityStatus: string;
   priorityLevel: string;
   slowSpeed: string;
   normalSpeed: string;
   fastSpeed: string;
   pauseSim: string;
   resumeSim: string;
   rmodeTitle: string;
   pntTitle: string;
   rmodeSimulator: string;
   hdopTitle: string;
   accuracyTitle: string;
   geometryTitle: string;
   stationId: string;
   dragHint: string;
   theoryTitle: string;
   geometricDilution: string;
   atomicClockTitle: string;
   toaDescription: string;
   jammingTitle: string;
   spoofingTitle: string;
   optimalScenario: string;
   poorScenario: string;
   criticalScenario: string;
   resetMap: string;
   packetDecoder: string;
   decodePayload: string;
   selectTemplate: string;
   rawPayload: string;
   layerSMMP: string;
   layerMMTP: string;
   layerNMEA: string;
   encryptionKey: string;
   routingHeader: string;
   radioSentences: string;
   stackType: string;
   vdesStack: string;
   ethernetStack: string;
   backhaulStack: string;
   layerTransport: string;
   layerPhysical: string;
   endToEnd: string;
   hopByHop: string;
   protocolIndependenceTitle: string;
   protocolIndependenceDesc: string;
   disclaimerTitle: string;
   disclaimerText: string;
   educationalApp: string;
   vdeSatView: string;
   vdeSatSimulator: string;
   satelliteTitle: string;
   dopplerShift: string;
   latencyTitle: string;
   footprintTitle: string;
   passDuration: string;
   accessMode: string;
   randomAccess: string;
   spreadSpectrumTitle: string;
   locking: string;
   passStatus: string;
   vdeSatExpTitle: string;
   vdeSatExpDesc: string;
   vdeSatDopplerTitle: string;
   vdeSatDopplerDesc: string;
   vdeSatLatencyTitle: string;
   vdeSatLatencyDesc: string;
   vdeSatEssaTitle: string;
   vdeSatEssaDesc: string;
   aisCongestionView: string;
   aisCongestionSimulator: string;
   shipDensity: string;
   slotOccupancy: string;
   radarBlindingRisk: string;
   mmsEdgeRouter: string;
   routingActive: string;
   congestionWarning: string;
   congestionCritical: string;
   scenarioMalacca: string;
   scenarioGibraltar: string;
   scenarioEnglishChannel: string;
   aisPriorityTitle: string;
   aisPriorityDesc: string;
   macLayerTitle: string;
   macLayerDesc: string;
   routerTitle: string;
   routerDesc: string;
   slantRange: string;
   elevationAngle: string;
   dopplerTooltip: string;
   latencyTooltip: string;
   passTooltip: string;
   modeTooltip: string;
   slantTooltip: string;
   elevationTooltip: string;
   // ── VDES Controller Integration ──
   vdesCtrlView: string;
   vdesCtrlChapter: string;
   vdesCtrlOverview: string;
   vdesCtrlWhy: string;
   vdesCtrlArchitecture: string;
   vdesCtrlProtocols: string;
   vdesCtrlAtoN: string;
   vdesCtrlHardware: string;
   vdesCtrlMMSRelation: string;
   vdesCtrlConfig: string;
   vdesCtrlFlow: string;
   vdesCtrlPitfalls: string;
   vdesCtrlRefs: string;
   vdesCtrlSubtitle: string;
   vdesCtrlOneLineTitle: string;
   vdesCtrlOneLineDesc: string;
   vdesCtrlStackTitle: string;
   vdesCtrlTechStackTitle: string;
   vdesCtrlWhyP1: string;
   vdesCtrlWhyP2: string;
   vdesCtrlWhyBullet1: string;
   vdesCtrlWhyBullet2: string;
   vdesCtrlWhyBullet3: string;
   vdesCtrlProtoDesc: string;
   vdesCtrlBBMExample: string;
   vdesCtrlUDPFlow: string;
   vdesCtrlPortNoteTitle: string;
   vdesCtrlPortNoteDesc: string;
   vdesCtrlPollingREST: string;
   vdesCtrlPollingPros: string;
   vdesCtrlPollingCons: string;
   vdesCtrlPollingWhen: string;
   vdesCtrlSubscribe: string;
   vdesCtrlSubscribePros: string;
   vdesCtrlSubscribeCons: string;
   vdesCtrlSubscribeWhen: string;
   vdesCtrlMappingTitle: string;
   vdesCtrlProdPath: string;
   vdesCtrlTestPath: string;
   vdesCtrlE320AdvTitle: string;
   vdesCtrlE320AdvDesc: string;
   vdesCtrlPyVdesTitle: string;
   vdesCtrlPyVdesDesc: string;
   vdesCtrlFundamentalTitle: string;
   vdesCtrlFundamentalDesc: string;
   vdesCtrlCompareTitle: string;
   vdesCtrlConvergeTitle: string;
   vdesCtrlConvergeDesc: string;
   vdesCtrlConfigExampleTitle: string;
   vdesCtrlQuickStartTitle: string;
   vdesCtrlStep1: string;
   vdesCtrlStep2: string;
   vdesCtrlStep3: string;
   vdesCtrlStep4: string;
   vdesCtrlStep5: string;
   vdesCtrlStep6: string;
   vdesCtrlStep7: string;
   vdesCtrlFlowTitle: string;
   vdesCtrlFlowSeq: string;
   vdesCtrlPitfallsTitle: string;
   vdesCtrlPitfall1Title: string;
   vdesCtrlPitfall1Desc: string;
   vdesCtrlPitfall2Title: string;
   vdesCtrlPitfall2Desc: string;
   vdesCtrlPitfall3Title: string;
   vdesCtrlPitfall3Desc: string;
   vdesCtrlPitfall4Title: string;
   vdesCtrlPitfall4Desc: string;
    vdesCtrlRefsTitle: string;
    vdesCtrlFooter: string;
    vdesCtrlEditLink: string;

    // ── TESLA Protocol (Chapter 4.4) ──
    teslaChapter: string;
    teslaTitle: string;
    teslaSubtitle: string;
    teslaSource: string;
    teslaEditLink: string;
    teslaFooterCredit: string;

    // 1. Problem
    teslaProblemTitle: string;
    teslaProblemP1: string;
    teslaProblemCalloutTitle: string;
    teslaProblemCallout1: string;
    teslaProblemCallout2: string;
    teslaProblemCallout3: string;
    teslaProblemCallout4: string;

    // 2. State of the Art
    teslaSotaTitle: string;
    teslaSotaHeader1: string;
    teslaSotaHeader2: string;
    teslaSotaHeader3: string;
    teslaSotaHeader4: string;
    teslaSotaRow1Col1: string;
    teslaSotaRow1Col2: string;
    teslaSotaRow1Col3: string;
    teslaSotaRow1Col4: string;
    teslaSotaRow2Col1: string;
    teslaSotaRow2Col2: string;
    teslaSotaRow2Col3: string;
    teslaSotaRow2Col4: string;
    teslaSotaRow3Col1: string;
    teslaSotaRow3Col2: string;
    teslaSotaRow3Col3: string;
    teslaSotaRow3Col4: string;
    teslaSotaCalloutTitle: string;
    teslaSotaCalloutContent: string;

    // 3. TESLA Intro
    teslaTeslaIntroTitle: string;
    teslaTeslaIntroP1: string;
    teslaSub1Title: string;
    teslaTeslaP2: string;
    teslaTeslaFormula: string;
    teslaTeslaP3: string;
    teslaTeslaCodeBlock1: string;

    // 4. Middleware
    teslaMiddlewareTitle: string;
    teslaMiddlewareP1: string;
    teslaMiddlewareCodeBlock: string;
    teslaOutOfBandTitle: string;
    teslaOutOfBand1: string;
    teslaOutOfBand2: string;
    teslaOutOfBand3: string;
    teslaOutOfBand4: string;
    teslaSub2Title: string;
    teslaTable2Header1: string;
    teslaTable2Header2: string;
    teslaTable2Header3: string;
    teslaTable2Row1Col1: string;
    teslaTable2Row1Col2: string;
    teslaTable2Row1Col3: string;
    teslaTable2Row2Col1: string;
    teslaTable2Row2Col2: string;
    teslaTable2Row2Col3: string;

    // 5. Parameters
    teslaParamsTitle: string;
    teslaParamsP1: string;
    teslaTable3Header1: string;
    teslaTable3Header2: string;
    teslaTable3Header3: string;
    teslaTable3Row1Col1: string;
    teslaTable3Row1Col2: string;
    teslaTable3Row1Col3: string;
    teslaTable3Row2Col1: string;
    teslaTable3Row2Col2: string;
    teslaTable3Row2Col3: string;
    teslaTable3Row3Col1: string;
    teslaTable3Row3Col2: string;
    teslaTable3Row3Col3: string;
    teslaSub3Title1: string;
    teslaParamsP2: string;
    teslaCodeBlock4: string;
    teslaSub3Title2: string;
    teslaTable4Header1: string;
    teslaTable4Header2: string;
    teslaTable4Header3: string;
    teslaTable4Header4: string;
    teslaTable4Row1Col1: string;
    teslaTable4Row1Col2: string;
    teslaTable4Row1Col3: string;
    teslaTable4Row1Col4: string;
    teslaTable4Row2Col1: string;
    teslaTable4Row2Col2: string;
    teslaTable4Row2Col3: string;
    teslaTable4Row2Col4: string;
    teslaTable4Row3Col1: string;
    teslaTable4Row3Col2: string;
    teslaTable4Row3Col3: string;
    teslaTable4Row3Col4: string;
    teslaCallout2Title: string;
    teslaCallout2Content: string;

    // 6. Messages
    teslaMessagesTitle: string;
    teslaMessagesP1: string;
    teslaSub4Title1: string;
    teslaTable5Header1: string;
    teslaTable5Header2: string;
    teslaTable5Header3: string;
    teslaTable5Header4: string;
    teslaTable5Row1Col1: string;
    teslaTable5Row1Col2: string;
    teslaTable5Row1Col3: string;
    teslaTable5Row1Col4: string;
    teslaTable5Row2Col1: string;
    teslaTable5Row2Col2: string;
    teslaTable5Row2Col3: string;
    teslaTable5Row2Col4: string;
    teslaTable5Row3Col1: string;
    teslaTable5Row3Col2: string;
    teslaTable5Row3Col3: string;
    teslaTable5Row3Col4: string;
    teslaCodeBlock5: string;
    teslaCallout3Title: string;
    teslaCallout3Content: string;
    teslaSub4Title2: string;
    teslaTable6Header1: string;
    teslaTable6Header2: string;
    teslaTable6Header3: string;
    teslaTable6Header4: string;
    teslaTable6Row1Col1: string;
    teslaTable6Row1Col2: string;
    teslaTable6Row1Col3: string;
    teslaTable6Row1Col4: string;
    teslaTable6Row2Col1: string;
    teslaTable6Row2Col2: string;
    teslaTable6Row2Col3: string;
    teslaTable6Row2Col4: string;
    teslaTable6Row3Col1: string;
    teslaTable6Row3Col2: string;
    teslaTable6Row3Col3: string;
    teslaTable6Row3Col4: string;
    teslaSub4Title3: string;
    teslaCodeBlock6: string;
    teslaCallout4Title: string;
    teslaCallout4Content: string;

    // 7. Sender
    teslaSenderTitle: string;
    teslaSenderP1: string;
    teslaCodeBlock7: string;
    teslaCallout5Title: string;
    teslaCallout5Content: string;

    // 8. Receiver
    teslaReceiverTitle: string;
    teslaReceiverP1: string;
    teslaSub5Title1: string;
    teslaTable7Header1: string;
    teslaTable7Header2: string;
    teslaTable7Header3: string;
    teslaTable7Header4: string;
    teslaTable7Row1Col1: string;
    teslaTable7Row1Col2: string;
    teslaTable7Row1Col3: string;
    teslaTable7Row1Col4: string;
    teslaTable7Row2Col1: string;
    teslaTable7Row2Col2: string;
    teslaTable7Row2Col3: string;
    teslaTable7Row2Col4: string;
    teslaReceiverP2: string;
    teslaSub5Title2: string;
    teslaTable8Header1: string;
    teslaTable8Header2: string;
    teslaTable8Header3: string;
    teslaTable8Row1Col1: string;
    teslaTable8Row1Col2: string;
    teslaTable8Row1Col3: string;
    teslaTable8Row2Col1: string;
    teslaTable8Row2Col2: string;
    teslaTable8Row2Col3: string;
    teslaTable8Row3Col1: string;
    teslaTable8Row3Col2: string;
    teslaTable8Row3Col3: string;
    teslaTable8Row4Col1: string;
    teslaTable8Row4Col2: string;
    teslaTable8Row4Col3: string;
    teslaSub5Title3: string;
    teslaCodeBlock8: string;
    teslaCallout6Title: string;
    teslaCallout6Content: string;

    // 9. Performance
    teslaPerfTitle: string;
    teslaPerfSub1: string;
    teslaTable9Header1: string;
    teslaTable9Header2: string;
    teslaTable9Header3: string;
    teslaTable9Row1Col1: string;
    teslaTable9Row1Col2: string;
    teslaTable9Row1Col3: string;
    teslaTable9Row2Col1: string;
    teslaTable9Row2Col2: string;
    teslaTable9Row2Col3: string;
    teslaTable9Row3Col1: string;
    teslaTable9Row3Col2: string;
    teslaTable9Row3Col3: string;
    teslaTable9Row4Col1: string;
    teslaTable9Row4Col2: string;
    teslaTable9Row4Col3: string;
    teslaPerfSub2: string;
    teslaCallout7Title: string;
    teslaCallout7Content: string;
    teslaPerfSub3: string;
    teslaTable10Header1: string;
    teslaTable10Header2: string;
    teslaTable10Header3: string;
    teslaTable10Row1Col1: string;
    teslaTable10Row1Col2: string;
    teslaTable10Row1Col3: string;
    teslaTable10Row2Col1: string;
    teslaTable10Row2Col2: string;
    teslaTable10Row2Col3: string;
    teslaTable10Row3Col1: string;
    teslaTable10Row3Col2: string;
    teslaTable10Row3Col3: string;

    // 10. Security
    teslaSecTitle: string;
    teslaSecTableHeader1: string;
    teslaSecTableHeader2: string;
    teslaSecTableHeader3: string;
    teslaSecTableRow1Col1: string;
    teslaSecTableRow1Col2: string;
    teslaSecTableRow1Col3: string;
    teslaSecTableRow2Col1: string;
    teslaSecTableRow2Col2: string;
    teslaSecTableRow2Col3: string;
    teslaSecTableRow3Col1: string;
    teslaSecTableRow3Col2: string;
    teslaSecTableRow3Col3: string;
    teslaSecTableRow4Col1: string;
    teslaSecTableRow4Col2: string;
    teslaSecTableRow4Col3: string;
    teslaSecTableRow5Col1: string;
    teslaSecTableRow5Col2: string;
    teslaSecTableRow5Col3: string;
    teslaCallout8Title: string;
    teslaCallout8Content: string;

    // 11. Takeaways
    teslaTakeawaysTitle: string;
    teslaCard1Title: string;
    teslaCard1Text: string;
    teslaCard2Title: string;
    teslaCard2Text: string;
    teslaCard3Title: string;
    teslaCard3Text: string;
    teslaCard4Title: string;
    teslaCard4Text: string;
    teslaQuizTitle: string;
    teslaQuiz1: string;
    teslaQuiz2: string;
    teslaQuiz3: string;
    teslaQuiz4: string;
    teslaQuiz5: string;
    teslaQuiz6: string;

    // 12. References
    teslaRefsTitle: string;
    teslaRef1Text: string;
    teslaRef2Text: string;
    teslaRef3Text: string;
    teslaRef4Text: string;
    teslaRef5Text: string;
    teslaRef6Text: string;
    teslaRef7Text: string;
    teslaRef8Text: string;

    [key: string]: string; // Allow additional keys
}

export interface BaseStation {
  id: string;
  x: number;
  y: number;
  active: boolean;
}

export type LocalizedString = { it: string; en: string };

export interface StepInfo {
  id: ComponentId;
  title: LocalizedString;
  subtitle: LocalizedString;
  details: LocalizedString[];
  protocol?: string;
  icon: React.ReactNode;
  resources?: Resource[];
  functioning?: {
    title: LocalizedString;
    steps: LocalizedString[];
  };
}

export interface Resource {
  title: string;
  url: string;
  type: 'spec' | 'paper' | 'use-case' | 'industry';
}

export interface SimPacket {
  id: string;
  type: 'SAR' | 'MET' | 'POS' | 'MALICIOUS' | 'TESLA';
  status: 'agent' | 'router' | 'link' | 'shore' | 'dest';
  link: 'vdes' | 'ip' | 'queued' | 'dropped';
  label: string;
  layer: 'Application' | 'Transport' | 'Physical' | 'Data';
  verified?: boolean;
  isTesla?: boolean;
}

export interface ProtocolInfo {
  id: string;
  name: string;
  description: LocalizedString;
  packetStructure: {
    field: string;
    description: LocalizedString;
    size?: string;
  }[];
  useCases: LocalizedString[];
  securityConsiderations: LocalizedString[];
  encapsulationStack?: string[];
  resources?: Resource[];
  functioning?: {
    title: LocalizedString;
    steps: LocalizedString[];
  };
}

export interface VdesChannelInfo {
  id: string;
  name: string;
  type: 'AIS' | 'ASM' | 'VDE-TER' | 'VDE-SAT';
  leg: 'upper' | 'lower' | 'simplex';
  frequency: string;
  channel: string;
  bandwidth: string;
  modulation: string;
  power: string;
  accessMethod: string;
  details: LocalizedString[];
  protocol: string;
  security: {
    confidentiality: LocalizedString;
    integrity: LocalizedString;
    availability: LocalizedString;
    notes: LocalizedString;
  };
}
